project:
  type: website
  output-dir: docs

website:
  title: "Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/pyjasmine
      - icon: linkedin
        href: https://www.linkedin.com/in/jasmine-marzouk/
format:
  html:
    theme: cosmo
    css: styles.css



