<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.313">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>portfolio – jasmine_m_stats_and_public_health_part-_2</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../../">
<script src="../../../site_libs/quarto-html/quarto.js"></script>
<script src="../../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="../../../styles.css">
</head>

<body class="nav-fixed fullcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../../index.html">
    <span class="navbar-title">portfolio</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content quarto-banner-title-block" id="quarto-document-content">



<div class="cell" data-execution_count="70">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy <span class="im">import</span> stats</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> norm</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> warnings</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>warnings.filterwarnings(<span class="st">'ignore'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="introduction" class="level1">
<h1>Introduction:</h1>
<p>West Nile Virus (WNV) is spread to people when they have been bitten by a mosquito carrying the virus. There are no vaccines to prevent the spread of the virus or treatments for the virus once it has infected a human. This is why it is important to monitor mosquito activity in the city to predict hotspots, especially during the hotter months, when there are more mosquitoes around. The following report will explore the data that has been gathered between 2007 to 2019 in order to build models that can predict WNV prevelance and monitor mosquito numbers in the city.</p>
<hr>
<section id="data-dictionary" class="level4">
<h4 class="anchored" data-anchor-id="data-dictionary">Data Dictionary:</h4>
<p><code>Year</code> :Year that the WNV test is performed <em>int64</em></p>
<p><code>Week</code> :Week that the WNV test is performed <em>int64</em></p>
<p><code>Address Block</code>: Address of the location of trap. <em>string</em></p>
<p><code>Block</code>: Block number of address <em>int64</em></p>
<p><code>Trap</code>: Id of the trap <em>string</em> - Some traps are “satellite traps”. These are traps that are set up near (usually within 6 blocks) an established trap to enhance surveillance efforts. Satellite traps are post fixed with letters. For example, T220A is a satellite trap to T220.</p>
<p><code>Trap type</code>: Type of trap <em>string</em></p>
<p><code>Date</code>: Date and time that the WNV test is performed <em>string</em> - Please note that not all the locations are tested at all times. Also, records exist only when a particular species of mosquitoes is found at a certain trap at a certain time.</p>
<p><code>Mosquito number</code>: Number of mosquitoes caught in this trap <em>int64</em> - These test results are organized in such a way that when the number of mosquitoes exceed 50, they are split into another record (another row in the dataset), such that the number of mosquitoes are capped at 50.</p>
<p><code>Mosquito ID</code>: Id for Mosquito species <em>string</em></p>
<p><code>WNV Present</code>: Whether West Nile Virus was present in these mosquitos string</p>
<p><code>Species</code>: Mosquito species <em>string</em></p>
<p><code>Lat</code>:Latitude of trap <em>float64</em></p>
<p><code>Lon</code>: Longitude of trap <em>float64</em></p>
<hr>
</section>
</section>
<section id="exploring-the-data" class="level1">
<h1>Exploring the Data:</h1>
<div class="cell" data-execution_count="2">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df <span class="op">=</span> pd.read_csv(<span class="st">'mosquito_data_part_2.csv'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="3">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>df.head(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="3">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Week</th>
      <th>Address Block</th>
      <th>Trap</th>
      <th>Trap type</th>
      <th>Date</th>
      <th>Mosquito number</th>
      <th>WNV Present</th>
      <th>Species</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>2019</td>
      <td>39</td>
      <td>100XX W OHARE AIRPORT</td>
      <td>T910</td>
      <td>GRAVID</td>
      <td>2019-09-26 00:09:00</td>
      <td>2</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
      <td>41.977738</td>
      <td>-87.880969</td>
      <td>9</td>
    </tr>
    <tr>
      <th>1</th>
      <td>2019</td>
      <td>39</td>
      <td>52XX S KOLMAR AVE</td>
      <td>T114</td>
      <td>GRAVID</td>
      <td>2019-09-26 00:09:00</td>
      <td>1</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
      <td>41.798211</td>
      <td>-87.736925</td>
      <td>9</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2019</td>
      <td>39</td>
      <td>58XX N WESTERN AVE</td>
      <td>T028</td>
      <td>GRAVID</td>
      <td>2019-09-26 00:09:00</td>
      <td>2</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
      <td>41.987245</td>
      <td>-87.689417</td>
      <td>9</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2019</td>
      <td>39</td>
      <td>39XX N SPRINGFIELD AVE</td>
      <td>T228</td>
      <td>GRAVID</td>
      <td>2019-09-26 00:09:00</td>
      <td>1</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
      <td>41.953664</td>
      <td>-87.724987</td>
      <td>9</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2019</td>
      <td>39</td>
      <td>131XX S BRANDON AVE</td>
      <td>T209</td>
      <td>GRAVID</td>
      <td>2019-09-26 00:09:00</td>
      <td>9</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
      <td>41.657069</td>
      <td>-87.546049</td>
      <td>9</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="4">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 18495 entries, 0 to 18494
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Year             18495 non-null  int64  
 1   Week             18495 non-null  int64  
 2   Address Block    18495 non-null  object 
 3   Trap             18495 non-null  object 
 4   Trap type        18495 non-null  object 
 5   Date             18495 non-null  object 
 6   Mosquito number  18495 non-null  int64  
 7   WNV Present      18495 non-null  object 
 8   Species          18495 non-null  object 
 9   Lat              18495 non-null  float64
 10  Lon              18495 non-null  float64
 11  Month            18495 non-null  int64  
dtypes: float64(2), int64(4), object(6)
memory usage: 1.7+ MB</code></pre>
</div>
</div>
<div class="cell" data-execution_count="5">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>df[<span class="st">'Mosquito number'</span>].describe()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="5">
<pre><code>count    18495.000000
mean        10.879913
std         13.475066
min          1.000000
25%          2.000000
50%          5.000000
75%         14.000000
max         50.000000
Name: Mosquito number, dtype: float64</code></pre>
</div>
</div>
<p>As mentioned in the introduction and what is evident from the data dictionary, we have rows that are duplicated due to how the mosquitos were capped at 50. So to deal with this, we will sum these rows together on the <code>Mosquito number</code> rows, this will mean that our Max: 50 mosquitos (see previous line of code) will change.</p>
<p>We will do this by grouping on all the columns except the <code>Mosquito number</code> column and then passing a sum on this, and assigning to a new dataframe <strong>df1</strong>. This will sum the duplicated rows by mosquito numbers, increasing our Max number of mosquitos in that column.</p>
<div class="cell" data-execution_count="6">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>df1 <span class="op">=</span> df.groupby([<span class="st">'Year'</span>, <span class="st">'Week'</span>, <span class="st">'Address Block'</span>, <span class="st">'Trap'</span>, <span class="st">'Trap type'</span>, <span class="st">'Date'</span>, <span class="st">'WNV Present'</span>, <span class="st">'Species'</span>, <span class="st">'Lat'</span>, <span class="st">'Lon'</span>, <span class="st">'Month'</span>]) <span class="op">\</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>.<span class="bu">sum</span>().reset_index()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>df1.describe().T</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="7">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>count</th>
      <th>mean</th>
      <th>std</th>
      <th>min</th>
      <th>25%</th>
      <th>50%</th>
      <th>75%</th>
      <th>max</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Year</th>
      <td>17391.0</td>
      <td>2012.851015</td>
      <td>3.733403</td>
      <td>2007.000000</td>
      <td>2010.000000</td>
      <td>2013.000000</td>
      <td>2016.000000</td>
      <td>2019.000000</td>
    </tr>
    <tr>
      <th>Week</th>
      <td>17391.0</td>
      <td>31.023748</td>
      <td>4.382891</td>
      <td>20.000000</td>
      <td>28.000000</td>
      <td>31.000000</td>
      <td>34.000000</td>
      <td>40.000000</td>
    </tr>
    <tr>
      <th>Lat</th>
      <td>17391.0</td>
      <td>41.848745</td>
      <td>0.114416</td>
      <td>41.644720</td>
      <td>41.746732</td>
      <td>41.867599</td>
      <td>41.962015</td>
      <td>42.017801</td>
    </tr>
    <tr>
      <th>Lon</th>
      <td>17391.0</td>
      <td>-87.706946</td>
      <td>0.091301</td>
      <td>-87.880969</td>
      <td>-87.764737</td>
      <td>-87.700238</td>
      <td>-87.643076</td>
      <td>-87.531051</td>
    </tr>
    <tr>
      <th>Month</th>
      <td>17391.0</td>
      <td>7.631764</td>
      <td>1.006986</td>
      <td>5.000000</td>
      <td>7.000000</td>
      <td>8.000000</td>
      <td>8.000000</td>
      <td>10.000000</td>
    </tr>
    <tr>
      <th>Mosquito number</th>
      <td>17391.0</td>
      <td>11.570582</td>
      <td>20.657879</td>
      <td>1.000000</td>
      <td>2.000000</td>
      <td>4.000000</td>
      <td>13.000000</td>
      <td>500.000000</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>Now we can see that our Max number of mosquitos is 500.</p>
<p>### Numerical columns:</p>
<p>Creating separate dataframes for the numerical and categorical data, to have better insight into the data, and this will help us with our analyses later on.</p>
<div class="cell" data-execution_count="8">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>numeric_cols <span class="op">=</span> <span class="bu">list</span>(df1.select_dtypes(<span class="st">'number'</span>).columns)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>numeric_cols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="8">
<pre><code>['Year', 'Week', 'Lat', 'Lon', 'Month', 'Mosquito number']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="9">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>df_num <span class="op">=</span> df1[numeric_cols]</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>df_num.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="9">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Week</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>11893</th>
      <td>2015</td>
      <td>31</td>
      <td>41.778305</td>
      <td>-87.754366</td>
      <td>8</td>
      <td>2</td>
    </tr>
    <tr>
      <th>3164</th>
      <td>2009</td>
      <td>23</td>
      <td>41.820859</td>
      <td>-87.665108</td>
      <td>6</td>
      <td>2</td>
    </tr>
    <tr>
      <th>2645</th>
      <td>2008</td>
      <td>33</td>
      <td>41.662387</td>
      <td>-87.590180</td>
      <td>8</td>
      <td>1</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>### Categorical columns:</p>
<div class="cell" data-execution_count="10">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>categ_cols <span class="op">=</span> <span class="bu">list</span>(df1.select_dtypes(<span class="st">'object'</span>).columns)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>categ_cols</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="10">
<pre><code>['Address Block', 'Trap', 'Trap type', 'Date', 'WNV Present', 'Species']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="11">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>df_cat <span class="op">=</span> df1[categ_cols]</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>df_cat.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="11">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Address Block</th>
      <th>Trap</th>
      <th>Trap type</th>
      <th>Date</th>
      <th>WNV Present</th>
      <th>Species</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2143</th>
      <td>100XX W OHARE</td>
      <td>T904</td>
      <td>GRAVID</td>
      <td>2008-07-01 00:07:00</td>
      <td>negative</td>
      <td>CULEX RESTUANS</td>
    </tr>
    <tr>
      <th>10136</th>
      <td>70XX N MOSELLE AVE</td>
      <td>T008</td>
      <td>GRAVID</td>
      <td>2014-08-07 00:08:00</td>
      <td>negative</td>
      <td>CULEX PIPIENS</td>
    </tr>
    <tr>
      <th>1220</th>
      <td>2XX E 111TH ST</td>
      <td>T084</td>
      <td>GRAVID</td>
      <td>2007-08-21 00:08:00</td>
      <td>positive</td>
      <td>CULEX PIPIENS</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>### Univariate analysis:</p>
<div class="cell" data-execution_count="14">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> df:</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>    <span class="co">#if column == 'X': adding customisation depending on a certain column X</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>        <span class="co">#plt.figure(figuresize=(10,5))</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    sns.histplot(data<span class="op">=</span>df, x<span class="op">=</span>col)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-7.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-8.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-9.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-10.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-11.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-13-output-12.png" class="img-fluid"></p>
</div>
</div>
<p>### Bivariate analysis:</p>
<p>A couple of questions come to mind while looking at the data, for this we will use the df1 data frame, as it still contains the <code>Trap type</code> column.</p>
<div class="cell" data-execution_count="15">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>traptype_mosqnum <span class="op">=</span> df1.groupby(<span class="st">'Trap type'</span>)[<span class="st">'Mosquito number'</span>].count()</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>traptype_mosqnum</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="15">
<pre><code>Trap type
CDC           474
GRAVID      16719
OVI             1
SENTINEL      197
Name: Mosquito number, dtype: int64</code></pre>
</div>
</div>
<p><em>Which Trap has caught the largest number of mosquitos</em>?</p>
<p>If we look at a simple count of Mosquito number against the trap types, it shows that 96% of the mosquitos were caught using the GRAVID trap.</p>
<div class="cell" data-execution_count="16">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>species_traptype <span class="op">=</span> df1.groupby(<span class="st">'Species'</span>)[<span class="st">'Trap type'</span>].value_counts(normalize<span class="op">=</span><span class="va">True</span>)<span class="op">*</span><span class="dv">100</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>sptrty_unstack <span class="op">=</span> species_traptype.unstack()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-execution_count="17">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>sptrty_unstack</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="17">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th>Trap type</th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>OVI</th>
      <th>SENTINEL</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>CULEX PIPIENS</th>
      <td>6.201849</td>
      <td>93.432203</td>
      <td>0.01926</td>
      <td>0.346687</td>
    </tr>
    <tr>
      <th>CULEX RESTUANS</th>
      <td>1.084697</td>
      <td>97.333454</td>
      <td>NaN</td>
      <td>1.581849</td>
    </tr>
    <tr>
      <th>CULEX SALINARIUS</th>
      <td>9.009009</td>
      <td>90.540541</td>
      <td>NaN</td>
      <td>0.450450</td>
    </tr>
    <tr>
      <th>CULEX TERRITANS</th>
      <td>1.312910</td>
      <td>98.358862</td>
      <td>NaN</td>
      <td>0.328228</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
<section id="part-1---basic-analysis" class="level1">
<h1>Part 1 - Basic Analysis</h1>
<section id="section" class="level2">
<h2 class="anchored" data-anchor-id="section">1.</h2>
<section id="converting-the-wnv-present-column-to-binary" class="level4">
<h4 class="anchored" data-anchor-id="converting-the-wnv-present-column-to-binary">1. Converting the <code>WNV Present</code> column to binary:</h4>
<p>In our DataFrame we have a column <code>WNV Presen</code> which shows us whether WNV virus was present in our test or not resent, denoted by Positive and Negative respectively. We can change this to a binary format using 1 and 0 as follows: - Positive = 1 - Negative = 0</p>
<div class="cell" data-execution_count="18">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Using the replace function to change the values in column WNV Present:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> row <span class="kw">in</span> df1[<span class="st">'WNV Present'</span>]:</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> row <span class="op">==</span> <span class="st">'positive'</span>:</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        df1[<span class="st">'WNV Present'</span>] <span class="op">=</span> df1[<span class="st">'WNV Present'</span>].replace([row], <span class="dv">1</span>)</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a>        df1[<span class="st">'WNV Present'</span>] <span class="op">=</span> df1[<span class="st">'WNV Present'</span>].replace([row], <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If we check our DataFram the <code>WNV Present</code> column should now contain 1 and 0.</p>
<div class="cell" data-execution_count="19">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>df1.sample(<span class="dv">5</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="19">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Week</th>
      <th>Address Block</th>
      <th>Trap</th>
      <th>Trap type</th>
      <th>Date</th>
      <th>WNV Present</th>
      <th>Species</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>11050</th>
      <td>2014</td>
      <td>38</td>
      <td>51XX N MONT CLARE AVE</td>
      <td>T223</td>
      <td>GRAVID</td>
      <td>2014-09-18 00:09:00</td>
      <td>1</td>
      <td>CULEX PIPIENS</td>
      <td>41.974530</td>
      <td>-87.804584</td>
      <td>9</td>
      <td>16</td>
    </tr>
    <tr>
      <th>3070</th>
      <td>2009</td>
      <td>21</td>
      <td>70XX W ARMITAGE AVE</td>
      <td>T151</td>
      <td>GRAVID</td>
      <td>2009-06-02 00:06:00</td>
      <td>0</td>
      <td>CULEX PIPIENS</td>
      <td>41.916135</td>
      <td>-87.801093</td>
      <td>6</td>
      <td>1</td>
    </tr>
    <tr>
      <th>15611</th>
      <td>2018</td>
      <td>30</td>
      <td>61XX N LEMONT AVE</td>
      <td>T012</td>
      <td>GRAVID</td>
      <td>2018-07-26 00:07:00</td>
      <td>0</td>
      <td>CULEX RESTUANS</td>
      <td>41.993564</td>
      <td>-87.745420</td>
      <td>7</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17092</th>
      <td>2019</td>
      <td>34</td>
      <td>3XX W 104TH ST</td>
      <td>T095</td>
      <td>GRAVID</td>
      <td>2019-08-22 00:08:00</td>
      <td>1</td>
      <td>CULEX RESTUANS</td>
      <td>41.705328</td>
      <td>-87.632947</td>
      <td>8</td>
      <td>1</td>
    </tr>
    <tr>
      <th>3295</th>
      <td>2009</td>
      <td>25</td>
      <td>75XX N OAKLEY AVE</td>
      <td>T148</td>
      <td>GRAVID</td>
      <td>2009-06-26 00:06:00</td>
      <td>0</td>
      <td>CULEX RESTUANS</td>
      <td>42.017801</td>
      <td>-87.687601</td>
      <td>6</td>
      <td>2</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
<section id="creating-dummy-variables-from-the-trap-type-column" class="level4">
<h4 class="anchored" data-anchor-id="creating-dummy-variables-from-the-trap-type-column">2. Creating dummy variables from the Trap type column</h4>
<p>using the <code>pd.get_dummies()</code> function, the variables in column <code>Trap type</code> will be split into separate columns containing 1 and 0. Each time a row coincides with a trap type, that row will have a 1 in the corresponding trap type column, and a 0 in the rest of the trap type columns. We will drop the <code>OVI</code> column that the function creates because it contains redundant information, as a value of 0 in each of the other columns is essentially the same as a 1 in the <code>OVI</code> column.</p>
<div class="cell" data-execution_count="20">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>df1[<span class="st">'Trap type'</span>].unique()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="20">
<pre><code>array(['GRAVID', 'CDC', 'OVI', 'SENTINEL'], dtype=object)</code></pre>
</div>
</div>
<div class="cell" data-execution_count="21">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>df2 <span class="op">=</span> pd.get_dummies(df1[<span class="st">"Trap type"</span>])</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>df2.drop(columns<span class="op">=</span>[<span class="st">'OVI'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>df2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="21">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>SENTINEL</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>17386</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17387</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17388</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17389</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17390</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>17391 rows × 3 columns</p>
</div>
</div>
</div>
<p>Next we concatenate our df2 (dummy variables matrix) to our df1 dataframe on the axis=1 to, also assigning this to a new dataframe df3, this should bring our columns number up to 16 columns.</p>
<div class="cell" data-scrolled="true" data-execution_count="22">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>df3 <span class="op">=</span> pd.concat([df1, df2], axis <span class="op">=</span> <span class="dv">1</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>df3.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="22">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Week</th>
      <th>Address Block</th>
      <th>Trap</th>
      <th>Trap type</th>
      <th>Date</th>
      <th>WNV Present</th>
      <th>Species</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>SENTINEL</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>14606</th>
      <td>2017</td>
      <td>33</td>
      <td>101XX S STONY ISLAND AVE</td>
      <td>T138B</td>
      <td>SENTINEL</td>
      <td>2017-08-17 00:08:00</td>
      <td>1</td>
      <td>CULEX RESTUANS</td>
      <td>41.710829</td>
      <td>-87.584526</td>
      <td>8</td>
      <td>96</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>1849</th>
      <td>2007</td>
      <td>38</td>
      <td>14XX N HUMBOLDT DR</td>
      <td>T033</td>
      <td>GRAVID</td>
      <td>2007-09-24 00:09:00</td>
      <td>0</td>
      <td>CULEX PIPIENS</td>
      <td>41.907285</td>
      <td>-87.701395</td>
      <td>9</td>
      <td>17</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>5665</th>
      <td>2011</td>
      <td>27</td>
      <td>100XX W OHARE AIRPORT</td>
      <td>T906</td>
      <td>GRAVID</td>
      <td>2011-07-11 00:07:00</td>
      <td>0</td>
      <td>CULEX RESTUANS</td>
      <td>41.977738</td>
      <td>-87.880969</td>
      <td>7</td>
      <td>44</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="23">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>df3.drop(columns<span class="op">=</span>[<span class="st">'Trap type'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Checking our dataframe to ensure the <code>Trap type</code> column has been dropped.</p>
<div class="cell" data-execution_count="27">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>df3.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 17391 entries, 0 to 17390
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Year             17391 non-null  int64  
 1   Week             17391 non-null  int64  
 2   Address Block    17391 non-null  object 
 3   Trap             17391 non-null  object 
 4   Date             17391 non-null  object 
 5   WNV Present      17391 non-null  int64  
 6   Species          17391 non-null  object 
 7   Lat              17391 non-null  float64
 8   Lon              17391 non-null  float64
 9   Month            17391 non-null  int64  
 10  Mosquito number  17391 non-null  int64  
 11  CDC              17391 non-null  uint8  
 12  GRAVID           17391 non-null  uint8  
 13  SENTINEL         17391 non-null  uint8  
dtypes: float64(2), int64(5), object(4), uint8(3)
memory usage: 1.5+ MB</code></pre>
</div>
</div>
<div class="cell" data-execution_count="28">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>df3.shape</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f'df3 datafram contains </span><span class="sc">{</span>df3<span class="sc">.</span>shape[<span class="dv">0</span>]<span class="sc">}</span><span class="ss"> rows and </span><span class="sc">{</span>df3<span class="sc">.</span>shape[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> columns'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>df3 datafram contains 17391 rows and 14 columns</code></pre>
</div>
</div>
<div class="cell" data-execution_count="29">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>df3.nunique().sort_values()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="29">
<pre><code>WNV Present           2
CDC                   2
GRAVID                2
SENTINEL              2
Species               4
Month                 6
Year                 13
Week                 21
Address Block       154
Mosquito number     175
Trap                190
Date                298
Lat                2509
Lon                2509
dtype: int64</code></pre>
</div>
</div>
</section>
<section id="updating-the-num_df-dataframe" class="level4">
<h4 class="anchored" data-anchor-id="updating-the-num_df-dataframe">Updating the <code>num_df</code> dataframe:</h4>
<p>Since we’ve added three new columns that have numerical values, we need to add these to our num_df dataframe.</p>
<div class="cell" data-execution_count="30">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>numeric_cols1 <span class="op">=</span> <span class="bu">list</span>(df3.select_dtypes(<span class="st">'number'</span>).columns)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>numeric_cols1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="30">
<pre><code>['Year',
 'Week',
 'WNV Present',
 'Lat',
 'Lon',
 'Month',
 'Mosquito number',
 'CDC',
 'GRAVID',
 'SENTINEL']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="31">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df_num1 <span class="op">=</span> df3[numeric_cols1]</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>df_num1.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="31">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Year</th>
      <th>Week</th>
      <th>WNV Present</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>SENTINEL</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7739</th>
      <td>2012</td>
      <td>38</td>
      <td>0</td>
      <td>41.883772</td>
      <td>-87.716168</td>
      <td>9</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>482</th>
      <td>2007</td>
      <td>29</td>
      <td>0</td>
      <td>41.704687</td>
      <td>-87.564236</td>
      <td>7</td>
      <td>55</td>
      <td>1</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>11378</th>
      <td>2015</td>
      <td>24</td>
      <td>0</td>
      <td>41.798211</td>
      <td>-87.736925</td>
      <td>6</td>
      <td>5</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<hr>
</section>
</section>
</section>
<section id="part-2---statistical-analysis" class="level1">
<h1>Part 2 - Statistical Analysis</h1>
<section id="investigating-statistical-significance-between-mosquito-species-and-west-nile-virus-occurance." class="level4">
<h4 class="anchored" data-anchor-id="investigating-statistical-significance-between-mosquito-species-and-west-nile-virus-occurance.">1. Investigating statistical significance between mosquito species and West Nile Virus occurance.</h4>
<p>What are we looking at? - Species: categorical, comprised of four different species, <em>CULEX RESTUANS</em>, <em>CULEX TERRITANS</em>, <em>CULEX SALINARIUS</em>, and <em>CULEX PIPIENS</em>. - WNV Present: binary, consiting of either a 1 or 0: 1 for <strong>Positive</strong> meaning these mosquitos carry the WNV, and 0 for <strong>Negative</strong>.</p>
<p>Defining our assumptions: - <span class="math inline">\(H_0\)</span>: There is no relationship between mosquito species and the occurance of WNV. - <span class="math inline">\(H_1\)</span>: There is <em>some relationship</em> between mosquito species and the occurance of WNV</p>
<p>To test for the statistical significance, we carry out a Chi2-contingency test, because we are comparing two categorical variables.</p>
<p>First, we create a <strong>contigency table</strong>, containing the different number of observations for each species of mosquito.</p>
<div class="cell" data-execution_count="32">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Grouping by species and the count of negative and positive tests for each:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>wnv_pre <span class="op">=</span> df3.groupby(<span class="st">'Species'</span>)[<span class="st">'WNV Present'</span>].value_counts().unstack().reset_index()</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co">#Renaming the columns of the table to make things clearer:</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>wnv_pre.columns <span class="op">=</span> [<span class="st">'Species'</span>, <span class="st">'wnv_negative'</span>, <span class="st">'wnv_positive'</span>]</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a><span class="co">#Setting species column as the index:</span></span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a>wnv_pre <span class="op">=</span> wnv_pre.set_index(<span class="st">'Species'</span>)</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a><span class="co">#Table view:</span></span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'Contigency table'</span>)</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>wnv_pre</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Contigency table</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="32">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>wnv_negative</th>
      <th>wnv_positive</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>CULEX PIPIENS</th>
      <td>3972</td>
      <td>1220</td>
    </tr>
    <tr>
      <th>CULEX RESTUANS</th>
      <td>9021</td>
      <td>2042</td>
    </tr>
    <tr>
      <th>CULEX SALINARIUS</th>
      <td>215</td>
      <td>7</td>
    </tr>
    <tr>
      <th>CULEX TERRITANS</th>
      <td>900</td>
      <td>14</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>A heatmap to better visualise the prevelance:</p>
<div class="cell" data-execution_count="33">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>cont_prop <span class="op">=</span> <span class="bu">round</span>((wnv_pre<span class="op">/</span>wnv_pre.<span class="bu">sum</span>())<span class="op">*</span><span class="dv">100</span>, <span class="dv">3</span>)</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>cont_prop</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="33">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>wnv_negative</th>
      <th>wnv_positive</th>
    </tr>
    <tr>
      <th>Species</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>CULEX PIPIENS</th>
      <td>28.154</td>
      <td>37.161</td>
    </tr>
    <tr>
      <th>CULEX RESTUANS</th>
      <td>63.942</td>
      <td>62.199</td>
    </tr>
    <tr>
      <th>CULEX SALINARIUS</th>
      <td>1.524</td>
      <td>0.213</td>
    </tr>
    <tr>
      <th>CULEX TERRITANS</th>
      <td>6.379</td>
      <td>0.426</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="34">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>sns.heatmap(wnv_pre,</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>            cmap<span class="op">=</span><span class="st">"Blues"</span>, annot<span class="op">=</span><span class="va">True</span>, cbar<span class="op">=</span><span class="va">False</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Contingency table as heatmap'</span>)</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-31-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell" data-execution_count="35">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(stats.chi2_contingency(wnv_pre))</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'    '</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> stats.chi2_contingency(wnv_pre)[<span class="dv">1</span>] <span class="op">&lt;</span> <span class="fl">0.05</span>:</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f'The p-value </span><span class="sc">{</span>stats<span class="sc">.</span>chi2_contingency(wnv_pre)[<span class="dv">1</span>]<span class="sc">}</span><span class="ss"> is &lt;0.05, thus statistically significant.'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(289.06184352112183, 2.317119160315453e-62, 3, array([[4211.87602783,  980.12397217],
       [8974.57328503, 2088.42671497],
       [ 180.09177161,   41.90822839],
       [ 741.45891553,  172.54108447]]))
    
The p-value 2.317119160315453e-62 is &lt;0.05, thus statistically significant.</code></pre>
</div>
</div>
<p>The p-value is very very small, this suggests that we reject our <span class="math inline">\(H_0\)</span> hypothesis, and that we have less than a 5% probability the null is correct (and the results are random). However, this does not mean that we have 95% probability that our <span class="math inline">\(H_1\)</span> is true, so we fail to reject it. &gt; But we can infer from what we have calculated that we could observe a relationship between mosquito species and the prevelance of WNV. However this depends on whether we can faily compare the numbers of specific species caught to infer that the species does account for prevelance of WNV. Furthermore, the way the testing is carried out further determines how we interpret what we are seeing in the data.</p>
<blockquote class="blockquote">
<p>Question: So if we have a particular species in a number of caught mosquitos does this increase our chances of getting a positive, how does this affect our analysis and does this cause issues in modelling?</p>
</blockquote>
</section>
<section id="investigating-correlations-with-the-number-of-mosquitoes-caught" class="level4">
<h4 class="anchored" data-anchor-id="investigating-correlations-with-the-number-of-mosquitoes-caught">2. Investigating correlations with the number of mosquitoes caught:</h4>
<p>correlation =</p>
<div class="cell" data-execution_count="36">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>plt.figure(figsize<span class="op">=</span>(<span class="dv">15</span>,<span class="dv">10</span>))</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>sns.heatmap(df3.corr(), annot<span class="op">=</span><span class="va">True</span>, cmap<span class="op">=</span><span class="st">'PuOr'</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-33-output-1.png" class="img-fluid"></p>
</div>
</div>
<p><strong>Observations</strong></p>
<p>Looking at the heatmap we don’t really notice any strong correlations between Mosquito numbers and the other columns that stand out, however there are correlations between the columns, most notably between Mosquito numbers and WNV Present. - <code>Mosquito number</code> is positively correlated with:</p>
<pre><code>- `SENTINEL`

- `CDC`

- `WNV Present`</code></pre>
<ul>
<li><p><code>Mosquito number</code> is negativly correlated with:</p>
<ul>
<li><p><code>GRAVID</code></p></li>
<li><p><code>Month</code></p></li>
<li><p><code>Week</code></p></li>
</ul></li>
</ul>
<p>To see the numbers up close, we will run the following code:</p>
<div class="cell" data-execution_count="37">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df3[df3.columns[<span class="dv">1</span>:]].corr()[<span class="st">'Mosquito number'</span>].sort_values()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="37">
<pre><code>Lon               -0.144528
GRAVID            -0.104599
Month             -0.030397
Week              -0.025767
SENTINEL           0.075084
CDC                0.075194
Lat                0.086622
WNV Present        0.336526
Mosquito number    1.000000
Name: Mosquito number, dtype: float64</code></pre>
</div>
</div>
<p>The strongest correlation, although still a weaker one, is between <code>Mosquito number</code> and <code>WNV present</code>.</p>
<p><em>How are mosquitos tested for WNV?</em>:</p>
<p>The mosquitos were tested in groups of counted mosquitos. So if a group of 10 mosquitos, for example, is tested we only get one result negative or positive for WNV, this is because the test is carried out by first homogenising (grinding the mosquitos) and then conducting the relavant laboratory techiques for RNA analysis, so if WNV genetic material is found the entire group of 10 mosquitos is considered a ‘positive’.</p>
<p>So the higher the number of mosquitos the test was performed on, the higher the probability of seeing a positive result, this creates a bias in the data, making it difficult to compare between groups of mosquito numbers and the prevelance of WNV.</p>
<p>We would see more relevant results if every mosquito caught was individually tested for the presence of WNV, however this is not efficient and would require a lot of resources.</p>
<p>To see whether these positive and negative correlations, although low, have any statistical significance. For that, we will create a loop code to run through all the correlations between Mosquito numbers and the rest of the numerical columns (using the numerical dataframe we created earlier)</p>
<div class="cell" data-execution_count="39">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>corr_df <span class="op">=</span> df_num1.drop(columns<span class="op">=</span>[<span class="st">'Mosquito number'</span>])</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> corr_df:</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>    corr <span class="op">=</span> stats.pearsonr(corr_df[col], df3[<span class="st">'Mosquito number'</span>])</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f'The Pearson correlation coefficient for </span><span class="sc">{</span>col<span class="sc">}</span><span class="ss"> is </span><span class="sc">{</span>corr[<span class="dv">0</span>]<span class="sc">}</span><span class="ss">, with a p-value of </span><span class="sc">{</span>corr[<span class="dv">1</span>]<span class="sc">}</span><span class="ss">'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The Pearson correlation coefficient for Year is 0.0977545480750341, with a p-value of 3.4086279685946815e-38
The Pearson correlation coefficient for Week is -0.02576712939076369, with a p-value of 0.0006779149465776343
The Pearson correlation coefficient for WNV Present is 0.33652604181940193, with a p-value of 0.0
The Pearson correlation coefficient for Lat is 0.08662203916220389, with a p-value of 2.5208184064825616e-30
The Pearson correlation coefficient for Lon is -0.1445281386907279, with a p-value of 8.152195157877397e-82
The Pearson correlation coefficient for Month is -0.030396647076333192, with a p-value of 6.092628690389725e-05
The Pearson correlation coefficient for CDC is 0.07519428649152668, with a p-value of 3.0953021153273027e-23
The Pearson correlation coefficient for GRAVID is -0.10459949490633716, with a p-value of 1.6566909067612184e-43
The Pearson correlation coefficient for SENTINEL is 0.0750844012267073, with a p-value of 3.581245504376958e-23</code></pre>
</div>
</div>
<p><strong>Plots of the all the numberical columns against the number of mosquitos counts</strong></p>
<div class="cell" data-execution_count="40">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> corr_df:</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>    sns.boxplot(x<span class="op">=</span>corr_df[col], y<span class="op">=</span>df3[<span class="st">'Mosquito number'</span>], showfliers<span class="op">=</span><span class="va">False</span>) </span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a><span class="co">#showfliers=False hides the outliers to better visualise the plots.</span></span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>    plt.title(<span class="ss">f'</span><span class="sc">{</span>col<span class="sc">}</span><span class="ss"> vs Number of Mosquitos '</span>)</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-1.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-6.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-7.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-8.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-36-output-9.png" class="img-fluid"></p>
</div>
</div>
<p>As we can see all the p-values are &lt; 0.05 suggesting statististical significance in the relationships between Mosquito number and the other columns.</p>
<hr>
</section>
</section>
<section id="linear-regression-model" class="level1">
<h1>Linear Regression Model</h1>
<p>We want to know if we can predict the number of mosquitos that we will catch in our traps using a linear regression model.</p>
<p>We saw that our dependent variable <code>Mosquito number</code> had statistically significant correlations with all our independent variables.</p>
<blockquote class="blockquote">
<p><strong>In other words, can we predict the number of mosquitoes we will catch in our traps using our other variables.</strong></p>
</blockquote>
<p>We will look at how the number of mosquitos caught is related to other variables in the study, such as week, year and the trap types. We would also like to look at how the species of the mosquitos has an effect on this. to do that we will create a new dataframe that contains dummy variables of the four species.</p>
<div class="cell" data-execution_count="41">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>df3[<span class="st">'Species'</span>].value_counts()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="41">
<pre><code>CULEX RESTUANS      11063
CULEX PIPIENS        5192
CULEX TERRITANS       914
CULEX SALINARIUS      222
Name: Species, dtype: int64</code></pre>
</div>
</div>
<div class="cell" data-execution_count="42">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creating dummy variables, and dropping one to avoid multicolinearity.</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>df_spec <span class="op">=</span> pd.get_dummies(df3[<span class="st">"Species"</span>])</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>df_spec.drop(columns<span class="op">=</span>[<span class="st">'CULEX SALINARIUS'</span>], inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>df_spec</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="42">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>CULEX PIPIENS</th>
      <th>CULEX RESTUANS</th>
      <th>CULEX TERRITANS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>1</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>4</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>17386</th>
      <td>0</td>
      <td>0</td>
      <td>1</td>
    </tr>
    <tr>
      <th>17387</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17388</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17389</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>17390</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
<p>17391 rows × 3 columns</p>
</div>
</div>
</div>
<div class="cell" data-scrolled="true" data-execution_count="43">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co">#concatenating df_spec to a new dataframe df4:</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>df4 <span class="op">=</span> pd.concat([df_spec, df3], axis <span class="op">=</span> <span class="dv">1</span>).reset_index(drop<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>df4.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="43">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>CULEX PIPIENS</th>
      <th>CULEX RESTUANS</th>
      <th>CULEX TERRITANS</th>
      <th>Year</th>
      <th>Week</th>
      <th>Address Block</th>
      <th>Trap</th>
      <th>Date</th>
      <th>WNV Present</th>
      <th>Species</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>SENTINEL</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>14877</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>2017</td>
      <td>37</td>
      <td>5XX W 72ND ST</td>
      <td>T035</td>
      <td>2017-09-14 00:09:00</td>
      <td>0</td>
      <td>CULEX RESTUANS</td>
      <td>41.763371</td>
      <td>-87.637873</td>
      <td>9</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8147</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>2013</td>
      <td>28</td>
      <td>39XX N SPRINGFIELD AVE</td>
      <td>T228</td>
      <td>2013-07-12 00:07:00</td>
      <td>1</td>
      <td>CULEX RESTUANS</td>
      <td>41.953668</td>
      <td>-87.724985</td>
      <td>7</td>
      <td>29</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>14795</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>2017</td>
      <td>36</td>
      <td>100XX W OHARE AIRPORT</td>
      <td>T910</td>
      <td>2017-09-08 00:09:00</td>
      <td>0</td>
      <td>CULEX RESTUANS</td>
      <td>41.977738</td>
      <td>-87.880969</td>
      <td>9</td>
      <td>7</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="44">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#adding these to a new numarical datafram:</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>numeric_cols2 <span class="op">=</span> <span class="bu">list</span>(df4.select_dtypes(<span class="st">'number'</span>).columns)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>numeric_cols2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="44">
<pre><code>['CULEX PIPIENS',
 'CULEX RESTUANS',
 'CULEX TERRITANS',
 'Year',
 'Week',
 'WNV Present',
 'Lat',
 'Lon',
 'Month',
 'Mosquito number',
 'CDC',
 'GRAVID',
 'SENTINEL']</code></pre>
</div>
</div>
<div class="cell" data-execution_count="45">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>df_num3 <span class="op">=</span> df4[numeric_cols2]</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>df_num3.sample(<span class="dv">3</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="45">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>CULEX PIPIENS</th>
      <th>CULEX RESTUANS</th>
      <th>CULEX TERRITANS</th>
      <th>Year</th>
      <th>Week</th>
      <th>WNV Present</th>
      <th>Lat</th>
      <th>Lon</th>
      <th>Month</th>
      <th>Mosquito number</th>
      <th>CDC</th>
      <th>GRAVID</th>
      <th>SENTINEL</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>4852</th>
      <td>0</td>
      <td>0</td>
      <td>0</td>
      <td>2010</td>
      <td>32</td>
      <td>0</td>
      <td>41.681035</td>
      <td>-87.533436</td>
      <td>8</td>
      <td>2</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>2505</th>
      <td>1</td>
      <td>0</td>
      <td>0</td>
      <td>2008</td>
      <td>31</td>
      <td>0</td>
      <td>41.965375</td>
      <td>-87.758412</td>
      <td>8</td>
      <td>1</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8361</th>
      <td>0</td>
      <td>1</td>
      <td>0</td>
      <td>2013</td>
      <td>30</td>
      <td>0</td>
      <td>41.987245</td>
      <td>-87.689417</td>
      <td>7</td>
      <td>3</td>
      <td>0</td>
      <td>1</td>
      <td>0</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>our new numerical data dataframe is df_num2, which now contains the Mosquito Species as binary columns.</p>
<p>now we can go ahead with creating our linear model.</p>
<section id="creating-independant-and-dependant-variables-x-and-y" class="level6">
<h6 class="anchored" data-anchor-id="creating-independant-and-dependant-variables-x-and-y">Creating Independant and Dependant variables (X and y)</h6>
<div class="cell" data-execution_count="46">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>df_num3.columns</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="46">
<pre><code>Index(['CULEX PIPIENS', 'CULEX RESTUANS', 'CULEX TERRITANS', 'Year', 'Week',
       'WNV Present', 'Lat', 'Lon', 'Month', 'Mosquito number', 'CDC',
       'GRAVID', 'SENTINEL'],
      dtype='object')</code></pre>
</div>
</div>
<div class="cell" data-execution_count="47">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>X_lin <span class="op">=</span> df_num3.drop(columns <span class="op">=</span> [<span class="st">'Mosquito number'</span>, <span class="st">'WNV Present'</span>]) <span class="co">#independent variables</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>y_lin <span class="op">=</span> df_num3[<span class="st">'Mosquito number'</span>] <span class="co">#dependent variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s look at what these variables look plotted against each other. We want to see if there is any visible linear trend between any of them and <code>Mosquito number</code>.</p>
<div class="cell" data-execution_count="48">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>plt.subplots(<span class="dv">4</span>,<span class="dv">3</span>, figsize<span class="op">=</span>(<span class="dv">20</span>,<span class="dv">15</span>))</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>count <span class="op">=</span> <span class="dv">1</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> col <span class="kw">in</span> X_lin.columns:</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>    plt.subplot(<span class="dv">4</span>,<span class="dv">3</span>,count)</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>    plt.scatter(X_lin[col],y_lin)</span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>    plt.title(col)</span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>    count <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>plt.tight_layout()</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-44-output-1.png" class="img-fluid"></p>
</div>
</div>
<p>There doesn’t seem to be any distinct linear trend in the plots. However, we can’t dismiss that our variables could fit a linear model. For example we can suspect that the time of year has an effect on mosquito numbers, and that the number of mosquitoes caught is dependent on the trap type. We can go further and also assume that trap types that are better at catching all species of mosquitoes will further affect numbers of mosquitoes caught. so we will test this in the following sections.</p>
</section>
<section id="modelling" class="level3">
<h3 class="anchored" data-anchor-id="modelling">Modelling</h3>
<div class="cell" data-execution_count="51">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="co">##### Adding constants</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a>X_lin_const <span class="op">=</span> sm.add_constant(X_lin)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="co">##### Instantiating our model</span></span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a>mosquito_model <span class="op">=</span> sm.OLS(y_lin, X_lin_const)</span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-9"><a href="#cb61-9" aria-hidden="true" tabindex="-1"></a><span class="co">##### Fit the model</span></span>
<span id="cb61-10"><a href="#cb61-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-11"><a href="#cb61-11" aria-hidden="true" tabindex="-1"></a>mosquito_results <span class="op">=</span> mosquito_model.fit()</span>
<span id="cb61-12"><a href="#cb61-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-13"><a href="#cb61-13" aria-hidden="true" tabindex="-1"></a><span class="co">##### Checking our Model</span></span>
<span id="cb61-14"><a href="#cb61-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-15"><a href="#cb61-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mosquito_results.summary())</span>
<span id="cb61-16"><a href="#cb61-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-17"><a href="#cb61-17" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual values</span></span>
<span id="cb61-18"><a href="#cb61-18" aria-hidden="true" tabindex="-1"></a>mosquito_residuals <span class="op">=</span> mosquito_results.resid</span>
<span id="cb61-19"><a href="#cb61-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-20"><a href="#cb61-20" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitted values</span></span>
<span id="cb61-21"><a href="#cb61-21" aria-hidden="true" tabindex="-1"></a>mosquito_fitvals <span class="op">=</span> mosquito_results.fittedvalues</span>
<span id="cb61-22"><a href="#cb61-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-23"><a href="#cb61-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-24"><a href="#cb61-24" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb61-25"><a href="#cb61-25" aria-hidden="true" tabindex="-1"></a>plt.hist(mosquito_residuals, bins <span class="op">=</span> <span class="dv">12</span>)</span>
<span id="cb61-26"><a href="#cb61-26" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Residuals'</span>)</span>
<span id="cb61-27"><a href="#cb61-27" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-28"><a href="#cb61-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-29"><a href="#cb61-29" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb61-30"><a href="#cb61-30" aria-hidden="true" tabindex="-1"></a>plt.scatter(mosquito_fitvals, mosquito_residuals)</span>
<span id="cb61-31"><a href="#cb61-31" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Fitted Values'</span>)</span>
<span id="cb61-32"><a href="#cb61-32" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb61-33"><a href="#cb61-33" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Scatter Plot of Residuals vs Fitted Values'</span>)</span>
<span id="cb61-34"><a href="#cb61-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-35"><a href="#cb61-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-36"><a href="#cb61-36" aria-hidden="true" tabindex="-1"></a><span class="co">#Q-Q plot</span></span>
<span id="cb61-37"><a href="#cb61-37" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb61-38"><a href="#cb61-38" aria-hidden="true" tabindex="-1"></a>stats.probplot(mosquito_residuals, dist<span class="op">=</span><span class="st">"norm"</span>, plot <span class="op">=</span> plt)<span class="op">;</span></span>
<span id="cb61-39"><a href="#cb61-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb61-40"><a href="#cb61-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-41"><a href="#cb61-41" aria-hidden="true" tabindex="-1"></a><span class="co">#Shapiro Wilk Test</span></span>
<span id="cb61-42"><a href="#cb61-42" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapiro-Wilk Test: "</span>, stats.shapiro(mosquito_residuals))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Mosquito number   R-squared:                       0.059
Model:                            OLS   Adj. R-squared:                  0.059
Method:                 Least Squares   F-statistic:                     99.95
Date:                Mon, 20 Jun 2022   Prob (F-statistic):          1.01e-221
Time:                        22:02:31   Log-Likelihood:                -76804.
No. Observations:               17391   AIC:                         1.536e+05
Df Residuals:                   17379   BIC:                         1.537e+05
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const           -4355.4870    187.155    -23.272      0.000   -4722.329   -3988.645
CULEX PIPIENS      10.6398      1.377      7.726      0.000       7.940      13.339
CULEX RESTUANS      9.4609      1.367      6.922      0.000       6.782      12.140
CULEX TERRITANS     0.7950      1.506      0.528      0.598      -2.156       3.746
Year                0.6241      0.046     13.498      0.000       0.533       0.715
Week               -0.1075      0.115     -0.934      0.350      -0.333       0.118
Lat                -8.6033      1.961     -4.386      0.000     -12.448      -4.759
Lon               -39.3953      2.462    -16.002      0.000     -44.221     -34.570
Month              -0.2454      0.501     -0.490      0.624      -1.227       0.737
CDC                24.6718     20.065      1.230      0.219     -14.658      64.002
GRAVID             11.1295     20.047      0.555      0.579     -28.164      50.423
SENTINEL           24.9554     20.102      1.241      0.214     -14.447      64.358
==============================================================================
Omnibus:                    21609.835   Durbin-Watson:                   1.462
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          5446062.164
Skew:                           6.599   Prob(JB):                         0.00
Kurtosis:                      88.683   Cond. No.                     2.48e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.48e+06. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-45-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-45-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-45-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapiro-Wilk Test:  (0.5731819868087769, 0.0)</code></pre>
</div>
</div>
<p><strong>Analysis</strong></p>
<p>We ran our model in a backwards stepwise selection, feeding it all the independent variables at once.</p>
<p>to interpret these results we will look at the p-values for each variable:</p>
<ul>
<li><p><code>CULEX TERRITANS</code>, <code>Week</code>, <code>CDC</code>, <code>GRAVID</code>, <code>Month</code>, <code>SENTINEL</code> have p-values&gt; 0.05, so according to our model there is no statistical significance to suggest these variables have an effect on the dependent variable (predicting <code>Mosquito number</code>) &gt;According to our model here, the month variable does not have a statistically significant affect on the number of mosquitoes caught. However, we know that during summer months when there are more mosquitoes around, we have better chances of catching mosquitoes in the traps.</p></li>
<li><p><code>CULEX PIPIENS</code>, <code>CULEX RESTUANS</code>, <code>Year</code>, <code>Lat</code>, and <code>Lon</code> have p-values &lt;0.05 showing statistical significance in the relationship between these independent variables and the dependent variable. In other terms, the number of Mosquitoes caught is affected by the changes in species year and location. &gt; However, in terms of <code>Lat</code> and <code>Lon</code>, although statistical significance is suggested by our model, it is hard to interpret in what way the relationship works, this would require further data wrangling to make this data nominal rather than continous.</p></li>
</ul>
<p>Moreover, our R2 value for this model is quite low 0.059, 5.9% of the variation in our dependent variable (Mosquito number) is explained by the model, further suggesting our model is a weak fit for the data, and that the relationship between our dependent and independent variables is weak. This is to be expected as we observed in earlier analyses that no linear relationships exist between our predictors (independent variables) and number of mosquito numbers, this is also due to the fact that our dependent variable (mosquito count) is count (distinct) data.</p>
<p><em>Resdiual Plots and Q-Q plot:</em></p>
<p>Looking at the scatter plot of our residuals (above), there is no clear linearity in the residuals, however there still seems to be a pattern in the data as opposed to random noise that would be equivilant to a normal distribution of the residuals.</p>
<p>The pattern also suggests heteroscedasticity, this further confirms that we don’t have linearity among our variables, however it also suggest non-normality of our residuals. this could be due to our values in <code>Mosquito number</code>, they range from 1 to a max of 500, this high variation in the counts could have an effect on our model.</p>
<p>Further, it could be that using a linear model for our regression analysis is an incorrect path, since our dependent variable is in counts, such as most ecology studies. However, this can be addressed by using a log transformation of our dependent variable to achieve normal distribution of our residuals.</p>
<div class="cell" data-execution_count="50">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="co">###### Using logarithmic transformation on the dependent variable and re-running the model</span></span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-3"><a href="#cb64-3" aria-hidden="true" tabindex="-1"></a>mosquito_numlog <span class="op">=</span> np.log(df_num3[<span class="st">'Mosquito number'</span>])</span>
<span id="cb64-4"><a href="#cb64-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-5"><a href="#cb64-5" aria-hidden="true" tabindex="-1"></a>X_lin1 <span class="op">=</span> df_num3.drop(columns <span class="op">=</span> [<span class="st">'Mosquito number'</span>, <span class="st">'WNV Present'</span>]) <span class="co">#independent variables</span></span>
<span id="cb64-6"><a href="#cb64-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-7"><a href="#cb64-7" aria-hidden="true" tabindex="-1"></a>y_lin1 <span class="op">=</span> mosquito_numlog <span class="co">#dependent variable</span></span>
<span id="cb64-8"><a href="#cb64-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-9"><a href="#cb64-9" aria-hidden="true" tabindex="-1"></a><span class="co">##### Adding constants</span></span>
<span id="cb64-10"><a href="#cb64-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-11"><a href="#cb64-11" aria-hidden="true" tabindex="-1"></a>X_lin_const1 <span class="op">=</span> sm.add_constant(X_lin1)</span>
<span id="cb64-12"><a href="#cb64-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-13"><a href="#cb64-13" aria-hidden="true" tabindex="-1"></a><span class="co">##### Instantiating our model</span></span>
<span id="cb64-14"><a href="#cb64-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-15"><a href="#cb64-15" aria-hidden="true" tabindex="-1"></a>mosquito_model1 <span class="op">=</span> sm.OLS(y_lin1, X_lin_const1)</span>
<span id="cb64-16"><a href="#cb64-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-17"><a href="#cb64-17" aria-hidden="true" tabindex="-1"></a><span class="co">##### Fit the model</span></span>
<span id="cb64-18"><a href="#cb64-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-19"><a href="#cb64-19" aria-hidden="true" tabindex="-1"></a>mosquito_results1 <span class="op">=</span> mosquito_model1.fit()</span>
<span id="cb64-20"><a href="#cb64-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-21"><a href="#cb64-21" aria-hidden="true" tabindex="-1"></a><span class="co">##### Checking our Model</span></span>
<span id="cb64-22"><a href="#cb64-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-23"><a href="#cb64-23" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mosquito_results1.summary())</span>
<span id="cb64-24"><a href="#cb64-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-25"><a href="#cb64-25" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual values</span></span>
<span id="cb64-26"><a href="#cb64-26" aria-hidden="true" tabindex="-1"></a>mosquito_resids1 <span class="op">=</span> mosquito_results1.resid</span>
<span id="cb64-27"><a href="#cb64-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-28"><a href="#cb64-28" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitted values</span></span>
<span id="cb64-29"><a href="#cb64-29" aria-hidden="true" tabindex="-1"></a>mosquito_fittedvalues1 <span class="op">=</span> mosquito_results1.fittedvalues</span>
<span id="cb64-30"><a href="#cb64-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-31"><a href="#cb64-31" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb64-32"><a href="#cb64-32" aria-hidden="true" tabindex="-1"></a>plt.hist(mosquito_resids1, bins <span class="op">=</span> <span class="dv">12</span>)</span>
<span id="cb64-33"><a href="#cb64-33" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Residuals'</span>)</span>
<span id="cb64-34"><a href="#cb64-34" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb64-35"><a href="#cb64-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-36"><a href="#cb64-36" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb64-37"><a href="#cb64-37" aria-hidden="true" tabindex="-1"></a>plt.scatter(mosquito_fittedvalues1, mosquito_resids1)</span>
<span id="cb64-38"><a href="#cb64-38" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Fitted Values'</span>)</span>
<span id="cb64-39"><a href="#cb64-39" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb64-40"><a href="#cb64-40" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Scatter Plot of Residuals vs Fitted Values'</span>)</span>
<span id="cb64-41"><a href="#cb64-41" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb64-42"><a href="#cb64-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-43"><a href="#cb64-43" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.gridspec <span class="im">import</span> GridSpec</span>
<span id="cb64-44"><a href="#cb64-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-45"><a href="#cb64-45" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb64-46"><a href="#cb64-46" aria-hidden="true" tabindex="-1"></a>gs <span class="op">=</span> GridSpec(<span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="cb64-47"><a href="#cb64-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-48"><a href="#cb64-48" aria-hidden="true" tabindex="-1"></a>ax_scatter <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb64-49"><a href="#cb64-49" aria-hidden="true" tabindex="-1"></a>ax_hist_x <span class="op">=</span> fig.add_subplot(gs[<span class="dv">0</span>,<span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb64-50"><a href="#cb64-50" aria-hidden="true" tabindex="-1"></a>ax_hist_y <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">3</span>])</span>
<span id="cb64-51"><a href="#cb64-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-52"><a href="#cb64-52" aria-hidden="true" tabindex="-1"></a>ax_scatter.scatter(mosquito_fittedvalues1, mosquito_resids1)</span>
<span id="cb64-53"><a href="#cb64-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-54"><a href="#cb64-54" aria-hidden="true" tabindex="-1"></a>ax_hist_x.hist(mosquito_resids1)</span>
<span id="cb64-55"><a href="#cb64-55" aria-hidden="true" tabindex="-1"></a>ax_hist_y.hist(mosquito_resids1, orientation <span class="op">=</span> <span class="st">'horizontal'</span>)</span>
<span id="cb64-56"><a href="#cb64-56" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb64-57"><a href="#cb64-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-58"><a href="#cb64-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-59"><a href="#cb64-59" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb64-60"><a href="#cb64-60" aria-hidden="true" tabindex="-1"></a>stats.probplot(mosquito_resids1, dist<span class="op">=</span><span class="st">"norm"</span>, plot <span class="op">=</span> plt)<span class="op">;</span></span>
<span id="cb64-61"><a href="#cb64-61" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb64-62"><a href="#cb64-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb64-63"><a href="#cb64-63" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapiro-Wilk Test: "</span>, stats.shapiro(mosquito_resids1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Mosquito number   R-squared:                       0.130
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     235.9
Date:                Mon, 20 Jun 2022   Prob (F-statistic):               0.00
Time:                        22:02:31   Log-Likelihood:                -27802.
No. Observations:               17391   AIC:                         5.563e+04
Df Residuals:                   17379   BIC:                         5.572e+04
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
===================================================================================
                      coef    std err          t      P&gt;|t|      [0.025      0.975]
-----------------------------------------------------------------------------------
const            -318.8824     11.181    -28.520      0.000    -340.798    -296.966
CULEX PIPIENS       1.3183      0.082     16.023      0.000       1.157       1.480
CULEX RESTUANS      1.2083      0.082     14.798      0.000       1.048       1.368
CULEX TERRITANS    -0.0383      0.090     -0.426      0.670      -0.215       0.138
Year                0.0621      0.003     22.489      0.000       0.057       0.068
Week                0.0062      0.007      0.904      0.366      -0.007       0.020
Lat                -0.6350      0.117     -5.419      0.000      -0.865      -0.405
Lon                -2.5044      0.147    -17.028      0.000      -2.793      -2.216
Month              -0.0762      0.030     -2.545      0.011      -0.135      -0.018
CDC                 2.2953      1.199      1.915      0.056      -0.054       4.645
GRAVID              1.5503      1.198      1.294      0.196      -0.797       3.898
SENTINEL            2.5257      1.201      2.103      0.035       0.172       4.880
==============================================================================
Omnibus:                      856.989   Durbin-Watson:                   1.271
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              582.108
Skew:                           0.335   Prob(JB):                    3.95e-127
Kurtosis:                       2.405   Cond. No.                     2.48e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.48e+06. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-46-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-46-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-46-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-46-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapiro-Wilk Test:  (0.9797584414482117, 1.317220556465328e-43)</code></pre>
</div>
</div>
<p>The log transformation has increased the fit of our model, although we do still have a low R2 (0.130).</p>
<p>We still need to take this a step further and drop all columns with p-values &gt; 0.05, because they are statistically insignificant to our model.</p>
<p>We will drop the following columns: <code>CULEX TERRITANS</code>, <code>Week</code>, <code>GRAVID</code></p>
<div class="cell" data-execution_count="52">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>mosquito_numlog <span class="op">=</span> np.log(df_num3[<span class="st">'Mosquito number'</span>])</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>X_lin2 <span class="op">=</span> df_num3.drop(columns <span class="op">=</span> [<span class="st">'Mosquito number'</span>, <span class="st">'WNV Present'</span>, <span class="st">'CULEX TERRITANS'</span>, <span class="st">'Week'</span>, <span class="st">'GRAVID'</span>]) <span class="co">#independent variables</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a>y_lin2 <span class="op">=</span> mosquito_numlog <span class="co">#dependent variable</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a><span class="co">##### Adding constants</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>X_lin_const2 <span class="op">=</span> sm.add_constant(X_lin2)</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a><span class="co">##### Instantiating our model</span></span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a>mosquito_model2 <span class="op">=</span> sm.OLS(y_lin2, X_lin_const2)</span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a><span class="co">##### Fit the model</span></span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a>mosquito_results2 <span class="op">=</span> mosquito_model2.fit()</span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a><span class="co">##### Checking our Model</span></span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mosquito_results2.summary())</span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-23"><a href="#cb67-23" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual values</span></span>
<span id="cb67-24"><a href="#cb67-24" aria-hidden="true" tabindex="-1"></a>mosquito_resids2 <span class="op">=</span> mosquito_results2.resid</span>
<span id="cb67-25"><a href="#cb67-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-26"><a href="#cb67-26" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitted values</span></span>
<span id="cb67-27"><a href="#cb67-27" aria-hidden="true" tabindex="-1"></a>mosquito_fittedvalues2 <span class="op">=</span> mosquito_results2.fittedvalues</span>
<span id="cb67-28"><a href="#cb67-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-29"><a href="#cb67-29" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb67-30"><a href="#cb67-30" aria-hidden="true" tabindex="-1"></a>plt.hist(mosquito_resids2, bins <span class="op">=</span> <span class="dv">12</span>)</span>
<span id="cb67-31"><a href="#cb67-31" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Residuals'</span>)</span>
<span id="cb67-32"><a href="#cb67-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb67-33"><a href="#cb67-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-34"><a href="#cb67-34" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb67-35"><a href="#cb67-35" aria-hidden="true" tabindex="-1"></a>plt.scatter(mosquito_fittedvalues2, mosquito_resids2)</span>
<span id="cb67-36"><a href="#cb67-36" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Fitted Values'</span>)</span>
<span id="cb67-37"><a href="#cb67-37" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb67-38"><a href="#cb67-38" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Scatter Plot of Residuals vs Fitted Values'</span>)</span>
<span id="cb67-39"><a href="#cb67-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb67-40"><a href="#cb67-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-41"><a href="#cb67-41" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.gridspec <span class="im">import</span> GridSpec</span>
<span id="cb67-42"><a href="#cb67-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-43"><a href="#cb67-43" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb67-44"><a href="#cb67-44" aria-hidden="true" tabindex="-1"></a>gs <span class="op">=</span> GridSpec(<span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="cb67-45"><a href="#cb67-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-46"><a href="#cb67-46" aria-hidden="true" tabindex="-1"></a>ax_scatter <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb67-47"><a href="#cb67-47" aria-hidden="true" tabindex="-1"></a>ax_hist_x <span class="op">=</span> fig.add_subplot(gs[<span class="dv">0</span>,<span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb67-48"><a href="#cb67-48" aria-hidden="true" tabindex="-1"></a>ax_hist_y <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">3</span>])</span>
<span id="cb67-49"><a href="#cb67-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-50"><a href="#cb67-50" aria-hidden="true" tabindex="-1"></a>ax_scatter.scatter(mosquito_fittedvalues2, mosquito_resids2)</span>
<span id="cb67-51"><a href="#cb67-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-52"><a href="#cb67-52" aria-hidden="true" tabindex="-1"></a>ax_hist_x.hist(mosquito_resids2)</span>
<span id="cb67-53"><a href="#cb67-53" aria-hidden="true" tabindex="-1"></a>ax_hist_y.hist(mosquito_resids2, orientation <span class="op">=</span> <span class="st">'horizontal'</span>)</span>
<span id="cb67-54"><a href="#cb67-54" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb67-55"><a href="#cb67-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-56"><a href="#cb67-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-57"><a href="#cb67-57" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb67-58"><a href="#cb67-58" aria-hidden="true" tabindex="-1"></a>stats.probplot(mosquito_resids2, dist<span class="op">=</span><span class="st">"norm"</span>, plot <span class="op">=</span> plt)<span class="op">;</span></span>
<span id="cb67-59"><a href="#cb67-59" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb67-60"><a href="#cb67-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-61"><a href="#cb67-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapiro-Wilk Test: "</span>, stats.shapiro(mosquito_resids2))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Mosquito number   R-squared:                       0.130
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     324.0
Date:                Mon, 20 Jun 2022   Prob (F-statistic):               0.00
Time:                        22:06:35   Log-Likelihood:                -27803.
No. Observations:               17391   AIC:                         5.562e+04
Df Residuals:                   17382   BIC:                         5.569e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const           -318.5777     11.037    -28.864      0.000    -340.211    -296.944
CULEX PIPIENS      1.3494      0.040     33.961      0.000       1.272       1.427
CULEX RESTUANS     1.2379      0.038     32.871      0.000       1.164       1.312
Year               0.0627      0.003     23.382      0.000       0.057       0.068
Lat               -0.6346      0.117     -5.416      0.000      -0.864      -0.405
Lon               -2.5054      0.147    -17.046      0.000      -2.794      -2.217
Month             -0.0504      0.010     -5.256      0.000      -0.069      -0.032
CDC                0.7426      0.058     12.870      0.000       0.630       0.856
SENTINEL           0.9756      0.087     11.233      0.000       0.805       1.146
==============================================================================
Omnibus:                      861.277   Durbin-Watson:                   1.270
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              582.884
Skew:                           0.335   Prob(JB):                    2.68e-127
Kurtosis:                       2.403   Cond. No.                     2.45e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.45e+06. This might indicate that there are
strong multicollinearity or other numerical problems.</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-47-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-47-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-47-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-47-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapiro-Wilk Test:  (0.9797160029411316, 1.2191296639625909e-43)</code></pre>
</div>
</div>
<p>After dropping the statistically insignificant models, not much has changed in our model. Further fitting we can drop <code>Lon</code> and <code>Lat</code> as it is difficult to get any meaningful correlation between geographical locations without some transformation first. Furthermore, we will also drop <code>Month</code> and <code>Year</code> as their coefficients are too low and thus do not inform on the prediction of mosquito numbers.</p>
<div class="cell" data-execution_count="54">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>mosquito_numlog <span class="op">=</span> np.log(df_num3[<span class="st">'Mosquito number'</span>])</span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>X_lin3 <span class="op">=</span> df_num3.drop(columns <span class="op">=</span> [<span class="st">'Mosquito number'</span>, <span class="st">'WNV Present'</span>, <span class="st">'CULEX TERRITANS'</span>, <span class="st">'Week'</span>, <span class="st">'GRAVID'</span>, <span class="st">'Lat'</span>, <span class="st">'Lon'</span>, <span class="st">'Month'</span>, <span class="st">'Year'</span>]) <span class="co">#independent variables</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a>y_lin3 <span class="op">=</span> mosquito_numlog <span class="co">#dependent variable</span></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a><span class="co">##### Adding constants</span></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a>X_lin_const3 <span class="op">=</span> sm.add_constant(X_lin3)</span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a><span class="co">##### Instantiating our model</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>mosquito_model3 <span class="op">=</span> sm.OLS(y_lin3, X_lin_const3)</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a><span class="co">##### Fit the model</span></span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>mosquito_results3 <span class="op">=</span> mosquito_model3.fit()</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-19"><a href="#cb70-19" aria-hidden="true" tabindex="-1"></a><span class="co">##### Checking our Model</span></span>
<span id="cb70-20"><a href="#cb70-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-21"><a href="#cb70-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(mosquito_results3.summary())</span>
<span id="cb70-22"><a href="#cb70-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-23"><a href="#cb70-23" aria-hidden="true" tabindex="-1"></a><span class="co">#Residual values</span></span>
<span id="cb70-24"><a href="#cb70-24" aria-hidden="true" tabindex="-1"></a>mosquito_resids3 <span class="op">=</span> mosquito_results3.resid</span>
<span id="cb70-25"><a href="#cb70-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-26"><a href="#cb70-26" aria-hidden="true" tabindex="-1"></a><span class="co">#Fitted values</span></span>
<span id="cb70-27"><a href="#cb70-27" aria-hidden="true" tabindex="-1"></a>mosquito_fittedvalues3 <span class="op">=</span> mosquito_results3.fittedvalues</span>
<span id="cb70-28"><a href="#cb70-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-29"><a href="#cb70-29" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb70-30"><a href="#cb70-30" aria-hidden="true" tabindex="-1"></a>plt.hist(mosquito_resids3, bins <span class="op">=</span> <span class="dv">12</span>)</span>
<span id="cb70-31"><a href="#cb70-31" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Histogram of Residuals'</span>)</span>
<span id="cb70-32"><a href="#cb70-32" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb70-33"><a href="#cb70-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-34"><a href="#cb70-34" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb70-35"><a href="#cb70-35" aria-hidden="true" tabindex="-1"></a>plt.scatter(mosquito_fittedvalues3, mosquito_resids3)</span>
<span id="cb70-36"><a href="#cb70-36" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">'Fitted Values'</span>)</span>
<span id="cb70-37"><a href="#cb70-37" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">'Residuals'</span>)</span>
<span id="cb70-38"><a href="#cb70-38" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">'Scatter Plot of Residuals vs Fitted Values'</span>)</span>
<span id="cb70-39"><a href="#cb70-39" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb70-40"><a href="#cb70-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-41"><a href="#cb70-41" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> matplotlib.gridspec <span class="im">import</span> GridSpec</span>
<span id="cb70-42"><a href="#cb70-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-43"><a href="#cb70-43" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">10</span>))</span>
<span id="cb70-44"><a href="#cb70-44" aria-hidden="true" tabindex="-1"></a>gs <span class="op">=</span> GridSpec(<span class="dv">4</span>, <span class="dv">4</span>)</span>
<span id="cb70-45"><a href="#cb70-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-46"><a href="#cb70-46" aria-hidden="true" tabindex="-1"></a>ax_scatter <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb70-47"><a href="#cb70-47" aria-hidden="true" tabindex="-1"></a>ax_hist_x <span class="op">=</span> fig.add_subplot(gs[<span class="dv">0</span>,<span class="dv">0</span>:<span class="dv">3</span>])</span>
<span id="cb70-48"><a href="#cb70-48" aria-hidden="true" tabindex="-1"></a>ax_hist_y <span class="op">=</span> fig.add_subplot(gs[<span class="dv">1</span>:<span class="dv">4</span>, <span class="dv">3</span>])</span>
<span id="cb70-49"><a href="#cb70-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-50"><a href="#cb70-50" aria-hidden="true" tabindex="-1"></a>ax_scatter.scatter(mosquito_fittedvalues3, mosquito_resids3)</span>
<span id="cb70-51"><a href="#cb70-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-52"><a href="#cb70-52" aria-hidden="true" tabindex="-1"></a>ax_hist_x.hist(mosquito_resids3)</span>
<span id="cb70-53"><a href="#cb70-53" aria-hidden="true" tabindex="-1"></a>ax_hist_y.hist(mosquito_resids3, orientation <span class="op">=</span> <span class="st">'horizontal'</span>)</span>
<span id="cb70-54"><a href="#cb70-54" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb70-55"><a href="#cb70-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-56"><a href="#cb70-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-57"><a href="#cb70-57" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb70-58"><a href="#cb70-58" aria-hidden="true" tabindex="-1"></a>stats.probplot(mosquito_resids3, dist<span class="op">=</span><span class="st">"norm"</span>, plot <span class="op">=</span> plt)<span class="op">;</span></span>
<span id="cb70-59"><a href="#cb70-59" aria-hidden="true" tabindex="-1"></a>plt.show()</span>
<span id="cb70-60"><a href="#cb70-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-61"><a href="#cb70-61" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Shapiro-Wilk Test: "</span>, stats.shapiro(mosquito_resids3))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                            OLS Regression Results                            
==============================================================================
Dep. Variable:        Mosquito number   R-squared:                       0.079
Model:                            OLS   Adj. R-squared:                  0.078
Method:                 Least Squares   F-statistic:                     371.2
Date:                Mon, 20 Jun 2022   Prob (F-statistic):          2.60e-307
Time:                        22:12:28   Log-Likelihood:                -28299.
No. Observations:               17391   AIC:                         5.661e+04
Df Residuals:                   17386   BIC:                         5.665e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==================================================================================
                     coef    std err          t      P&gt;|t|      [0.025      0.975]
----------------------------------------------------------------------------------
const              0.3093      0.037      8.455      0.000       0.238       0.381
CULEX PIPIENS      1.2780      0.040     31.640      0.000       1.199       1.357
CULEX RESTUANS     1.3653      0.038     35.552      0.000       1.290       1.441
CDC                0.4138      0.058      7.141      0.000       0.300       0.527
SENTINEL           1.0927      0.088     12.360      0.000       0.919       1.266
==============================================================================
Omnibus:                     1081.275   Durbin-Watson:                   1.193
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              690.294
Skew:                           0.364   Prob(JB):                    1.27e-150
Kurtosis:                       2.350   Cond. No.                         11.7
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.</code></pre>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-48-output-2.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-48-output-3.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-48-output-4.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-48-output-5.png" class="img-fluid"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Shapiro-Wilk Test:  (0.9587694406509399, 0.0)</code></pre>
</div>
</div>
<p>Our model is as follows:</p>
<p><span class="math display">\[ log(y) = 1.2780x_1 + 1.3653x_2 + 0.4138x_3 + 1.0927x_4 + 0.3093 \]</span></p>
<p><em>Interpretation</em>:</p>
<p>According to our model we can predict the number of mosquitos caught by the presence of two species of mosquitoes and the type of traps used.</p>
<ul>
<li>The presence of CULEX PIPIENS, there is a 1.2780 increase in number of mosquitos caught.</li>
<li>the presence of CULEX RESTUANS, there is a 1.3653 increase in number of mosquitos caught.</li>
<li>The use of CDC traps means an 0.4138 increase in number of mosquitos caught.</li>
<li>The use of SENTINEL, there is a 0.3093 increase in number of mosquitos caught.</li>
</ul>
<p>Further, because our dependent variable was log transformed we would have to apply an inverse transformation to get our predictions from the mode, that equation would be as follows:</p>
<p><span class="math display">\[ e^{log(y)} \]</span></p>
<hr>
</section>
</section>
<section id="logistic-regression-model" class="level1">
<h1>Logistic Regression Model</h1>
<div class="cell" data-execution_count="75">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>df4.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 17391 entries, 0 to 17390
Data columns (total 17 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   CULEX PIPIENS    17391 non-null  uint8  
 1   CULEX RESTUANS   17391 non-null  uint8  
 2   CULEX TERRITANS  17391 non-null  uint8  
 3   Year             17391 non-null  int64  
 4   Week             17391 non-null  int64  
 5   Address Block    17391 non-null  object 
 6   Trap             17391 non-null  object 
 7   Date             17391 non-null  object 
 8   WNV Present      17391 non-null  int64  
 9   Species          17391 non-null  object 
 10  Lat              17391 non-null  float64
 11  Lon              17391 non-null  float64
 12  Month            17391 non-null  int64  
 13  Mosquito number  17391 non-null  int64  
 14  CDC              17391 non-null  uint8  
 15  GRAVID           17391 non-null  uint8  
 16  SENTINEL         17391 non-null  uint8  
dtypes: float64(2), int64(5), object(4), uint8(6)
memory usage: 1.6+ MB</code></pre>
</div>
</div>
<div class="cell" data-execution_count="76">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The independent variables</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>X_logi <span class="op">=</span> df4.drop(columns <span class="op">=</span> [<span class="st">'WNV Present'</span>, <span class="st">'Address Block'</span>, <span class="st">'Species'</span>, <span class="st">'Trap'</span>, <span class="st">'Date'</span>, ])</span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The dependent variable</span></span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>y_logi <span class="op">=</span> df4[<span class="st">'WNV Present'</span>]</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-6"><a href="#cb75-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding constants</span></span>
<span id="cb75-7"><a href="#cb75-7" aria-hidden="true" tabindex="-1"></a>X_logi_const <span class="op">=</span> sm.add_constant(X_logi)</span>
<span id="cb75-8"><a href="#cb75-8" aria-hidden="true" tabindex="-1"></a>X_logi_const.head()</span>
<span id="cb75-9"><a href="#cb75-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-10"><a href="#cb75-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate model</span></span>
<span id="cb75-11"><a href="#cb75-11" aria-hidden="true" tabindex="-1"></a>wnv_model <span class="op">=</span> sm.Logit(y_logi, X_logi_const)</span>
<span id="cb75-12"><a href="#cb75-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb75-13"><a href="#cb75-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb75-14"><a href="#cb75-14" aria-hidden="true" tabindex="-1"></a>wnv_model_results <span class="op">=</span> wnv_model.fit()</span>
<span id="cb75-15"><a href="#cb75-15" aria-hidden="true" tabindex="-1"></a>wnv_model_results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Warning: Maximum number of iterations has been exceeded.
         Current function value: 0.395050
         Iterations: 35</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="76">

<table class="simpletable">
<caption>Logit Regression Results</caption>
<tbody><tr>
  <th>Dep. Variable:</th>      <td>WNV Present</td>   <th>  No. Observations:  </th>  <td> 17391</td> 
</tr>
<tr>
  <th>Model:</th>                 <td>Logit</td>      <th>  Df Residuals:      </th>  <td> 17378</td> 
</tr>
<tr>
  <th>Method:</th>                 <td>MLE</td>       <th>  Df Model:          </th>  <td>    12</td> 
</tr>
<tr>
  <th>Date:</th>            <td>Tue, 21 Jun 2022</td> <th>  Pseudo R-squ.:     </th>  <td>0.1845</td> 
</tr>
<tr>
  <th>Time:</th>                <td>00:36:49</td>     <th>  Log-Likelihood:    </th> <td> -6870.3</td>
</tr>
<tr>
  <th>converged:</th>             <td>False</td>      <th>  LL-Null:           </th> <td> -8424.9</td>
</tr>
<tr>
  <th>Covariance Type:</th>     <td>nonrobust</td>    <th>  LLR p-value:       </th>  <td> 0.000</td> 
</tr>
</tbody></table>
<table class="simpletable">
<tbody><tr>
         <td></td>            <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P&gt;|z|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>const</th>           <td> -266.6566</td> <td> 1759.762</td> <td>   -0.152</td> <td> 0.880</td> <td>-3715.727</td> <td> 3182.414</td>
</tr>
<tr>
  <th>CULEX PIPIENS</th>   <td>    1.4874</td> <td>    0.393</td> <td>    3.789</td> <td> 0.000</td> <td>    0.718</td> <td>    2.257</td>
</tr>
<tr>
  <th>CULEX RESTUANS</th>  <td>    1.1556</td> <td>    0.392</td> <td>    2.947</td> <td> 0.003</td> <td>    0.387</td> <td>    1.924</td>
</tr>
<tr>
  <th>CULEX TERRITANS</th> <td>   -1.1208</td> <td>    0.476</td> <td>   -2.357</td> <td> 0.018</td> <td>   -2.053</td> <td>   -0.189</td>
</tr>
<tr>
  <th>Year</th>            <td>    0.1156</td> <td>    0.007</td> <td>   16.136</td> <td> 0.000</td> <td>    0.102</td> <td>    0.130</td>
</tr>
<tr>
  <th>Week</th>            <td>    0.0956</td> <td>    0.017</td> <td>    5.699</td> <td> 0.000</td> <td>    0.063</td> <td>    0.128</td>
</tr>
<tr>
  <th>Lat</th>             <td>    0.4929</td> <td>    0.288</td> <td>    1.713</td> <td> 0.087</td> <td>   -0.071</td> <td>    1.057</td>
</tr>
<tr>
  <th>Lon</th>             <td>    0.0665</td> <td>    0.357</td> <td>    0.186</td> <td> 0.852</td> <td>   -0.634</td> <td>    0.767</td>
</tr>
<tr>
  <th>Month</th>           <td>    0.1809</td> <td>    0.072</td> <td>    2.499</td> <td> 0.012</td> <td>    0.039</td> <td>    0.323</td>
</tr>
<tr>
  <th>Mosquito number</th> <td>    0.0459</td> <td>    0.001</td> <td>   35.521</td> <td> 0.000</td> <td>    0.043</td> <td>    0.048</td>
</tr>
<tr>
  <th>CDC</th>             <td>   11.2917</td> <td> 1759.547</td> <td>    0.006</td> <td> 0.995</td> <td>-3437.357</td> <td> 3459.940</td>
</tr>
<tr>
  <th>GRAVID</th>          <td>   11.2822</td> <td> 1759.547</td> <td>    0.006</td> <td> 0.995</td> <td>-3437.366</td> <td> 3459.931</td>
</tr>
<tr>
  <th>SENTINEL</th>        <td>   11.1443</td> <td> 1759.547</td> <td>    0.006</td> <td> 0.995</td> <td>-3437.504</td> <td> 3459.793</td>
</tr>
</tbody></table>
</div>
</div>
<p>The p-value for the constant is &gt; 0.05, this is odd, we will re-create our model while dropping the predictors that have p-values &gt; 0.05 as they are not statistically signifanct to our model and don’t predict presence of WNV.</p>
<p><strong>Re-running the model</strong></p>
<p>Re-running the model, while dropping <code>Lon</code>, <code>Lat</code>, <code>CDC</code>, <code>GRAVID</code>, and <code>SENTINEL</code></p>
<div class="cell" data-execution_count="78">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The independent variables</span></span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a>X_logi <span class="op">=</span> df4.drop(columns <span class="op">=</span> [<span class="st">'WNV Present'</span>, <span class="st">'Address Block'</span>, <span class="st">'Species'</span>, <span class="st">'Trap'</span>, <span class="st">'Date'</span>, <span class="st">'Lon'</span>, <span class="st">'Lat'</span>, <span class="st">'CDC'</span>, <span class="st">'GRAVID'</span>, <span class="st">'SENTINEL'</span> ])</span>
<span id="cb77-3"><a href="#cb77-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The dependent variable</span></span>
<span id="cb77-4"><a href="#cb77-4" aria-hidden="true" tabindex="-1"></a>y_logi <span class="op">=</span> df4[<span class="st">'WNV Present'</span>]</span>
<span id="cb77-5"><a href="#cb77-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-6"><a href="#cb77-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-7"><a href="#cb77-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Adding constants</span></span>
<span id="cb77-8"><a href="#cb77-8" aria-hidden="true" tabindex="-1"></a>X_logi_const <span class="op">=</span> sm.add_constant(X_logi)</span>
<span id="cb77-9"><a href="#cb77-9" aria-hidden="true" tabindex="-1"></a>X_logi_const.head()</span>
<span id="cb77-10"><a href="#cb77-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-11"><a href="#cb77-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Instantiate model</span></span>
<span id="cb77-12"><a href="#cb77-12" aria-hidden="true" tabindex="-1"></a>wnv_model <span class="op">=</span> sm.Logit(y_logi, X_logi_const)</span>
<span id="cb77-13"><a href="#cb77-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb77-14"><a href="#cb77-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb77-15"><a href="#cb77-15" aria-hidden="true" tabindex="-1"></a>wnv_model_results <span class="op">=</span> wnv_model.fit()</span>
<span id="cb77-16"><a href="#cb77-16" aria-hidden="true" tabindex="-1"></a>wnv_model_results.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.395237
         Iterations 8</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="78">

<table class="simpletable">
<caption>Logit Regression Results</caption>
<tbody><tr>
  <th>Dep. Variable:</th>      <td>WNV Present</td>   <th>  No. Observations:  </th>  <td> 17391</td> 
</tr>
<tr>
  <th>Model:</th>                 <td>Logit</td>      <th>  Df Residuals:      </th>  <td> 17383</td> 
</tr>
<tr>
  <th>Method:</th>                 <td>MLE</td>       <th>  Df Model:          </th>  <td>     7</td> 
</tr>
<tr>
  <th>Date:</th>            <td>Tue, 21 Jun 2022</td> <th>  Pseudo R-squ.:     </th>  <td>0.1841</td> 
</tr>
<tr>
  <th>Time:</th>                <td>00:43:07</td>     <th>  Log-Likelihood:    </th> <td> -6873.6</td>
</tr>
<tr>
  <th>converged:</th>             <td>True</td>       <th>  LL-Null:           </th> <td> -8424.9</td>
</tr>
<tr>
  <th>Covariance Type:</th>     <td>nonrobust</td>    <th>  LLR p-value:       </th>  <td> 0.000</td> 
</tr>
</tbody></table>
<table class="simpletable">
<tbody><tr>
         <td></td>            <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P&gt;|z|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>const</th>           <td> -240.3808</td> <td>   13.931</td> <td>  -17.255</td> <td> 0.000</td> <td> -267.684</td> <td> -213.077</td>
</tr>
<tr>
  <th>CULEX PIPIENS</th>   <td>    1.4884</td> <td>    0.393</td> <td>    3.787</td> <td> 0.000</td> <td>    0.718</td> <td>    2.259</td>
</tr>
<tr>
  <th>CULEX RESTUANS</th>  <td>    1.1596</td> <td>    0.393</td> <td>    2.954</td> <td> 0.003</td> <td>    0.390</td> <td>    1.929</td>
</tr>
<tr>
  <th>CULEX TERRITANS</th> <td>   -1.1211</td> <td>    0.476</td> <td>   -2.356</td> <td> 0.018</td> <td>   -2.054</td> <td>   -0.188</td>
</tr>
<tr>
  <th>Year</th>            <td>    0.1155</td> <td>    0.007</td> <td>   16.701</td> <td> 0.000</td> <td>    0.102</td> <td>    0.129</td>
</tr>
<tr>
  <th>Week</th>            <td>    0.0957</td> <td>    0.017</td> <td>    5.717</td> <td> 0.000</td> <td>    0.063</td> <td>    0.129</td>
</tr>
<tr>
  <th>Month</th>           <td>    0.1794</td> <td>    0.072</td> <td>    2.484</td> <td> 0.013</td> <td>    0.038</td> <td>    0.321</td>
</tr>
<tr>
  <th>Mosquito number</th> <td>    0.0461</td> <td>    0.001</td> <td>   36.438</td> <td> 0.000</td> <td>    0.044</td> <td>    0.049</td>
</tr>
</tbody></table>
</div>
</div>
<div class="cell" data-execution_count="100">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Looking at our coefficients for our model</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>params <span class="op">=</span> <span class="bu">round</span>(wnv_model_results.params, <span class="dv">3</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="100">
<pre><code>const             -240.381
CULEX PIPIENS        1.488
CULEX RESTUANS       1.160
CULEX TERRITANS     -1.121
Year                 0.116
Week                 0.096
Month                0.179
Mosquito number      0.046
dtype: float64</code></pre>
</div>
</div>
<p>Our model is as follows:</p>
<p><span class="math display">\[ s(X) = P(y|X) = \frac{1}{1+e^{-(-240.381 + 1.488 x_1 + 1.160 x_2 - 1.121 x_3 + 0.116 x_4
                                   + 0.096 x_5 + 1.179 x_6 + 0.046 x_7)}} \]</span></p>
<div class="cell" data-execution_count="115">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co">#Storing our parameters into variables and finding the odds ratio for the predictors:</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>beta0 <span class="op">=</span> wnv_model_results.params[<span class="dv">0</span>]</span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>beta1 <span class="op">=</span> wnv_model_results.params[<span class="dv">1</span>]</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>beta2 <span class="op">=</span> wnv_model_results.params[<span class="dv">2</span>]</span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>beta3 <span class="op">=</span> wnv_model_results.params[<span class="dv">3</span>]</span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>beta4 <span class="op">=</span> wnv_model_results.params[<span class="dv">4</span>]</span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>beta5 <span class="op">=</span> wnv_model_results.params[<span class="dv">5</span>]</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a>beta6 <span class="op">=</span> wnv_model_results.params[<span class="dv">6</span>]</span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a>beta7 <span class="op">=</span> wnv_model_results.params[<span class="dv">7</span>]</span>
<span id="cb81-12"><a href="#cb81-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb81-13"><a href="#cb81-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> i <span class="kw">in</span> params:</span>
<span id="cb81-14"><a href="#cb81-14" aria-hidden="true" tabindex="-1"></a>    betai <span class="op">=</span> np.exp(params)</span>
<span id="cb81-15"><a href="#cb81-15" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="bu">round</span>(betai, <span class="dv">3</span>))</span>
<span id="cb81-16"><a href="#cb81-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">break</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>const              0.000
CULEX PIPIENS      4.428
CULEX RESTUANS     3.190
CULEX TERRITANS    0.326
Year               1.123
Week               1.101
Month              1.196
Mosquito number    1.047
dtype: float64</code></pre>
</div>
</div>
<p>This means that with one unit increase in the presense of CULEX PIPIENS species of mosquitoes, the odds of testing positive for WNV is increased by a factor of 4.428.</p>
<p>Furthermore, with one unit increase of Mosquito number, the odds of the pool of mosquitoes testing positive for WNV increases by 1.047. This makes sense since we know that according to how the mosquito testing is carried out (homogenisation) the larger the number of mosquitoes in the pool the more likely there would be presence of WNV. The same goes for Month, CULEX PIPIENS as we know the time of year and species has relevancy in terms of presence of the WNV; the hotter months mean more mosquitoes, and some species of mosquitoes are major vectors of WNV.</p>
<p>There is a decrease in odds of getting a positive result from a pool of mosquitoes, if there is a one unit increase of CULEX TERRITANS as the odds ratio is &lt; 1.</p>
<div class="cell" data-execution_count="116">
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a>coef_df <span class="op">=</span> pd.DataFrame({<span class="st">"coef"</span>: wnv_model_results.params, <span class="st">"odds_ratio"</span>: np.exp(wnv_model_results.params)})</span>
<span id="cb83-2"><a href="#cb83-2" aria-hidden="true" tabindex="-1"></a>coef_df</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display" data-execution_count="116">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>coef</th>
      <th>odds_ratio</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>const</th>
      <td>-240.380831</td>
      <td>4.017276e-105</td>
    </tr>
    <tr>
      <th>CULEX PIPIENS</th>
      <td>1.488378</td>
      <td>4.429904e+00</td>
    </tr>
    <tr>
      <th>CULEX RESTUANS</th>
      <td>1.159617</td>
      <td>3.188713e+00</td>
    </tr>
    <tr>
      <th>CULEX TERRITANS</th>
      <td>-1.121065</td>
      <td>3.259324e-01</td>
    </tr>
    <tr>
      <th>Year</th>
      <td>0.115544</td>
      <td>1.122483e+00</td>
    </tr>
    <tr>
      <th>Week</th>
      <td>0.095736</td>
      <td>1.100469e+00</td>
    </tr>
    <tr>
      <th>Month</th>
      <td>0.179375</td>
      <td>1.196470e+00</td>
    </tr>
    <tr>
      <th>Mosquito number</th>
      <td>0.046052</td>
      <td>1.047129e+00</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell" data-execution_count="117">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a>coef_df[<span class="st">"odds_ratio"</span>].sort_values().plot(kind<span class="op">=</span><span class="st">"bar"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>plt.axhline(y<span class="op">=</span><span class="dv">1</span>, c<span class="op">=</span><span class="st">"gray"</span>, linestyle<span class="op">=</span><span class="st">"--"</span>)</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a>plt.title(<span class="st">"Odds ratio"</span>)</span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-display">
<p><img src="jasmine_m_stats_and_public_health_part _2_files/figure-html/cell-55-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a>x_points <span class="op">=</span> np.arange(<span class="dv">0</span>, <span class="dv">7</span>, <span class="fl">0.01</span>)</span>
<span id="cb85-2"><a href="#cb85-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-3"><a href="#cb85-3" aria-hidden="true" tabindex="-1"></a>linear_combination <span class="op">=</span> <span class="fl">2.369</span> <span class="op">*</span> x_points <span class="op">-</span> <span class="fl">4.822</span></span>
<span id="cb85-4"><a href="#cb85-4" aria-hidden="true" tabindex="-1"></a>probability_of_being_hired <span class="op">=</span> sigmoid_curve(linear_combination)</span>
<span id="cb85-5"><a href="#cb85-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb85-6"><a href="#cb85-6" aria-hidden="true" tabindex="-1"></a>plt.figure()</span>
<span id="cb85-7"><a href="#cb85-7" aria-hidden="true" tabindex="-1"></a>plt.plot(x_points, probability_of_being_hired)</span>
<span id="cb85-8"><a href="#cb85-8" aria-hidden="true" tabindex="-1"></a>plt.grid()</span>
<span id="cb85-9"><a href="#cb85-9" aria-hidden="true" tabindex="-1"></a>plt.xlim(<span class="dv">0</span>,<span class="dv">7</span>)</span>
<span id="cb85-10"><a href="#cb85-10" aria-hidden="true" tabindex="-1"></a>plt.xlabel(<span class="st">"Hours Researching Role"</span>)</span>
<span id="cb85-11"><a href="#cb85-11" aria-hidden="true" tabindex="-1"></a>plt.ylabel(<span class="st">"p - Probability of Being Hired"</span>)</span>
<span id="cb85-12"><a href="#cb85-12" aria-hidden="true" tabindex="-1"></a>plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<hr>
</section>
<section id="references" class="level1">
<h1>References:</h1>
<p>https://pubmed.ncbi.nlm.nih.gov/23401954/</p>
<p>https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6025230/</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>